### PR TITLE
added my name

### PR DESCRIPTION
**Pull request by copperstick6**
added my name

### CODE REVIEW

**Comment by rdelfin** [comment]
YOU LEFT TWO FREAKING .DS_STORE FILES FREAKING SERIOUSLY

**Comment by copperstick6** [comment]
sorry macbook

**Comment by rdelfin** [comment]
Screw your sh...

**Comment by copperstick6** [comment]
YES. LESSON HERE: DON'T LET YOUR DREAMS BE MEMES... errr I mean MEMES BE DREAMS

**Pull request merged**
